version: '3'

services:
  bot:
    build: .
    container_name: ticket-bot
    environment:
      - TOKEN
    networks:
      - net
    depends_on:
      - pgsql
    restart: on-failure
    volumes:
      - /opt/ticket-bot/config:/app/config
  pgsql:
    image: postgres:15.3-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - net
    volumes:
      - /opt/ticket-bot/pgsql:/var/lib/postgresql/data
    restart: on-failure

networks:
  net:
    driver: bridge