name: Source Check

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [review_requested, ready_for_review]

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18]

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ matrix.os }}-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}

      - name: npm i
        if: steps.cache-node_modules.outputs.cache-hit != 'true' || github.event_name == 'pull_request'
        run: npm i --no-audit --force

      - name: ESLint
        run: npm run lint:check

      - name: build
        run: npm run build --if-present
